# Macro file for example B4
# 
# To be run preferably in batch, without graphics:
# % exampleB4[a,b,c,d] run2.mac
#
#/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0
#
/run/initialize
#
# Default kinemtics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1000 events
#
/tracking/verbose 1
/gps/particle ion
/gps/ion 27 60 0 0
/gps/position 0 0 0
/gps/energy 0. eV
/run/printProgress 1
/run/beamOn 100000
#/gps/particle electron
#/gps/energy 5 MeV
#/gps/List
